name: .NET Core for Jenkins

on:
  push:
    branches:
        - main
  pull_request:
    branches: 
        - main

jobs:

  build:

    runs-on: ubuntu-latest  

    steps:
    - name: Checkout
      uses: actions/checkout@v4
     
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build 
    
    - name: Execute unit tests
      run: dotnet test

    